config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails
  resources :cocktails do
  	resources :doses, only: [ :new, :create, :delete ]
  	#resources :doses, only: [ :new, :create ]
  end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	has_many :doses, dependent: :destroy
	has_many :ingredients, through: :doses
	has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
  	@cocktails = Cocktail.all
  end

  def show
  	@cocktail = Cocktail.find(params[:id])
  end

  def new
  	@cocktail = Cocktail.new
  end

  def create
	@cocktail = Cocktail.new(cocktail_params)
	  if @cocktail.save
      redirect_to cocktail_path(@cocktail[:id])
    else
      render :new
    end   
  end

  def edit
	@cocktail = Cocktail.find(params[:id]) 	 
  end

  def update
  	cocktail = Cocktail.find(params[:id])
  	cocktail.update(cocktail_params)

    redirect_to cocktail_path(@cocktail)
  end   

  def destroy
  	cocktail = Cocktail.find(params[:id])
  	cocktail.destroy(cocktail_params)

    redirect_to cocktail_path(@cocktail)
  end	

  def cocktail_params
  	params.require(:cocktail).permit(:name, :doses, :ingredients, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
  	@cocktail = Cocktail.find(params[:cocktail_id])
  	@dose = Dose.new
  end

  def create
  	@cocktail = Cocktail.find(params[:cocktail_id])
  	@dose = Dose.new(dose_params)
  	@dose.cocktail = @cocktail
  	if @dose.save
  	  redirect_to cocktail_path(@cocktail)
  	else
  	  render :new
    end
  end

  def destroy
  	@cocktail = Cocktail.find(params[:cocktail_id])
  	@doses = Dose.destroy
  end	
  
  def doses_params
  	params.require(:ingredient).permit(:ingredient)
  end	
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  #def new
  	#@cocktail = Cocktail.find(params[:cocktail_id])
  	#@ingredient = Ingredient.new
  #end

  #def delete
  	#@cocktail = Cocktail.find(params[:cocktail_id])
  	#@ingredient = Ingredient.destroy
  #end
  
  #def ingredient_params
  	#params.require(:ingredient).permit(:doses)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1>All Cocktails!</h1>
  <%= cl_image_tag("ddomrvp8xrrbfnfvd4sn",
      width: 400, height: 300, crop: :fill) %>
  
  <ul>
    <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
    <% end %>
  </ul>
<br>
  <br>
<%= link_to "Add a cocktail", new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<h1>
  <%= @cocktail.name %>
</h1>
<small>
  <%#= link_to "Delete", cocktail_path(@), method: :delete, data: { confirm: "Are you sure?" } %>
</small>
<%= link_to "add a dose",new_cocktail_dose_path(@cocktail)%>

<h2>Ingredients</h2>
<ul>
	<li></li>

	
</ul>

<%= link_to "Edit #{@cocktail.name}", edit_cocktail_path(@cocktail) %>
<br>
<br>
<%= link_to "All cocktails", cocktail_path %>

app/views/doses/show.html.erb
<div class="container">
<h1>Add an ingredient</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.input :photo, as: :file %>
  <%= cl_image_tag @article.photo.key, height: 300, width: 400, crop: :fill %>
  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %> 
<br>
<%= link_to "return to cocktails", cocktails_path  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>